version: '3.10'

services:

  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - './backend:/app'
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env 

  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080