version: '3.10'

services:

  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - './backend:/app'
    command: uvicorn main:app --reload --env-file uvicorn.env
    env_file:
      - .env 
    environment:
      - FRONTEND_URL=https://honkai-pictures.ru

  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    environment:
      - VUE_APP_BACKEND_URL=https://honkai-pictures.ru/api
    command: npm run build

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './frontend/dist:/app'      
      - './certs:/certs:ro'
    links:
      - backend