version: '3.10'

services:

  backend:
    build: ./backend
    volumes:
      - './backend:/app'
    command: uvicorn main:app --port 8000 --host 0.0.0.0
    env_file:
      - .env 
    environment:
      - FRONTEND_URL=https://pixiv.sbs

  frontend:
    build:
      context: ./frontend
      args:
        - VUE_APP_BACKEND_URL=https://pixiv.sbs/api
    ports:
      - 80:80
      - 443:443
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './certs:/certs'