version: '3.10'

services:

  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - './backend:/app'
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env 
    environment:
      - FRONTEND_URL=http://192.168.2.1

  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    environment:
      - VUE_APP_BACKEND_URL=http://192.168.2.1:8000
    command: npm run build

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './frontend/dist:/app'