version: '3.10'

services:

  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - './backend:/app'
    command: uvicorn main:app --port 8000 --host 0.0.0.0
    env_file:
      - .env 
    environment:
      - FRONTEND_URL=https://*.pixiv.sbs

  frontend:
    build: ./frontend
    environment:
      - VUE_APP_BACKEND_URL=https://pixiv.sbs/api

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './frontend/dist:/app'
      - './certs:/certs'