version: '3.10'

services:

  backend:
    restart: unless-stopped
    build: ./backend
    volumes:
      - './backend:/app'
    command: python3 main.py
    env_file:
      - .env 
    environment:
      - SITE_URL=https://pixiv.sbs

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      args:
        - VUE_APP_BACKEND_URL=https://pixiv.sbs/api
    ports:
      - 8001:443
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './certs:/certs'
    environment:
      - VIRTUAL_HOST=pixiv.sbs,www.pixiv.sbs
      - VIRTUAL_PORT=8001
      - LETSENCRYPT_HOST=pixiv.sbs,www.pixiv.sbs

networks:
  default:
    external:
      name: net